modLoader="javafml" #mandatory
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="gregtech_beyond_coremod"
version="0.0.1"
displayName="GregTech Beyond Coremod"
authors="blocky"
description='''Adds new GregTech Modern content.'''

[[dependencies.gregtech_beyond_coremod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side="BOTH"

[[dependencies.gregtech_beyond_coremod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.gregtech_beyond_coremod]]
modId="gtceu"
mandatory=true
versionRange="[${gtceu_version},)"
ordering="AFTER"
side="BOTH"