modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="gregtechbeyond_coremod"
version="0.0.1"
displayName="GregTech Beyond Coremod"
authors="blocky"
description='''Adds new GregTech Modern content.'''

[[dependencies.gregtechbeyond_coremod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.gregtechbeyond_coremod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.gregtechbeyond_coremod]]
modId="gtceu"
mandatory=true
versionRange="[${gtceu_version},)"
ordering="AFTER"
side="BOTH"